#!/bin/ksh -x

export RUN_ENVIR=${RUN_ENVIR:-"nco"}
export PS4='$SECONDS + '
date


#############################
# Source relevant config files
#############################
export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
configs="base"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done


##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}
export COMPONENT=${COMPONENT:-atmos}
GDATE=$($NDATE -06 $CDATE)
gPDY=$(echo $GDATE | cut -c1-8)
gcyc=$(echo $GDATE | cut -c9-10)

##############################################
# Clear job stat
##############################################
ecflow_client --alter clear_flag zombie /cycled_v16_3/primary/${cyc}/workflow_manager/v1.0/cycled/workflow_monitor

##############################################
# Check archive job status
##############################################
cd $offline_archive_job_dir
Failed_Dump_MissMatch=`grep "incompatable analysis and observation date/timeamsuabufr" ${offline_archive_job_dir}/*_atmos_analysis_*.o*|wc -l`
if [ $Failed_Dump_MissMatch -gt 0 ]; then
  echo "Found dump missmatch issue. Stop parallel"
  exit 901
fi
OFFLINE_ARCHIVE_fcount=`grep "+status=" *_HPSS_ARCHIVE_*.out|grep -v "=0"|grep -v "=72"|wc -l`
echo "Current found failed OFFLINE ARCHIVE jobs count is: $OFFLINE_ARCHIVE_fcount"
#if [ $OFFLINE_ARCHIVE_fcount -gt 0 ]; then
#  exit 901
#fi
OFFLINE_ARCHIVE_fcount=`grep " exceeded limit " *_HPSS_ARCHIVE_*.out|wc -l`
echo "Current OFFLINE ARCHIVE jobs exceeded clock limit count is: $OFFLINE_ARCHIVE_fcount"
#if [ $OFFLINE_ARCHIVE_fcount -gt 0 ]; then
#  exit 902
#fi
OFFLINE_ARCHIVE_fcount=`grep " - aborting" *_HPSS_ARCHIVE_*.out|wc -l`
echo "Current OFFLINE ARCHIVE jobs with aborting error count is: $OFFLINE_ARCHIVE_fcount"
#if [ $OFFLINE_ARCHIVE_fcount -gt 0 ]; then
#  exit 903
#fi

# Check from PDYm7 to PDY and start cleanup from first
for pdy_to_chk in ${PDYm7} ${PDYm6} ${PDYm5} ${PDYm4} ${PDYm3} ${PDYm2} ${PDYm1}
do
  mark_it="YES"
  ct_tmp=`ls *_HPSS_ARCHIVE_*_${pdy_to_chk}${cyc}.sh|wc -l`
  ct_tmp1=`grep "HTAR: HTAR SUCCESSFUL" *_HPSS_ARCHIVE_*_${pdy_to_chk}${cyc}.out|wc -l`
  if [ ! $ct_tmp -eq $ct_tmp1 ]; then mark_it=NO; fi
  if [ $mark_it = "YES" ]; then
   ecflowlog="$EXPDIR/logs/${pdy_to_chk}${cyc}.log"
   echo "This cycle should be removed" >> $ecflowlog 
   mv *_HPSS_ARCHIVE_*_${pdy_to_chk}${cyc}.out ./OLD
   export CDUMP=gfs
   export CDATE=${pdy_to_chk}${cyc}
   ${HOME_emc_ecf_wm}/scripts/global_offline_cleanup.sh
   export CDUMP=gdas
   export CDATE=${pdy_to_chk}${cyc}
   ${HOME_emc_ecf_wm}/scripts/global_offline_cleanup.sh
   export CDUMP=gdas
   export CDATE=${pdy_to_chk}${cyc}
   ${HOME_emc_ecf_wm}/scripts/enkfgdas_offline_cleanup.sh
  fi
done

mkdir -p $DATA
cd $DATA
##############################################
# Ensure obsproc input exist
##############################################

COMPONENT="atmos"

OBSPROC_GDAS_Trigger=$(compath.py ${envir}/obsproc/${obsproc_ver})/gdas.${PDY}/${cyc}/${COMPONENT}/gdas.t${cyc}z.updated.status.tm00.bufr_d
IMSSNOW_GDAS_Trigger=$(compath.py ${envir}/obsproc/${obsproc_ver})/gdas.${PDY}/${cyc}/${COMPONENT}/gdas.t${cyc}z.imssnow96.grib2
OBSPROC_GFS_Trigger=$(compath.py ${envir}/obsproc/${obsproc_ver})/gfs.${PDY}/${cyc}/${COMPONENT}/gfs.t${cyc}z.updated.status.tm00.bufr_d
IMSSNOW_gfs_Trigger=$(compath.py ${envir}/obsproc/${obsproc_ver})/gfs.${PDY}/${cyc}/${COMPONENT}/gfs.t${cyc}z.imssnow96.grib2
COMIN_OBS_gfs=$(compath.py prod/obsproc/${obsproc_ver})/gfs.$PDY/$cyc/${COMPONENT}/gfs.$cycle.prepbufr
COMIN_OBS_gdas=$(compath.py prod/obsproc/${obsproc_ver})/gdas.$PDY/$cyc/${COMPONENT}/gdas.$cycle.prepbufr

global_dump_dir_gdas=${DMPDIR}/gdas.${PDY}/${cyc}/atmos/gdas.t${cyc}z.updated.status.tm00.bufr_d
global_dump_dir_gfs=${DMPDIR}/gfs.${PDY}/${cyc}/atmos/gfs.t${cyc}z.updated.status.tm00.bufr_d
if [ -f $global_dump_dir_gdas ]; then
  echo "Found $global_dump_dir_gdas"
  # ecflow_client --event release_gdas_emc_prep
else
  sleep 200
  exit 95
fi
if [ -f $global_dump_dir_gfs ]; then
  echo "Found $global_dump_dir_gfs"
  #ecflow_client --event release_gfs_emc_prep
else
  sleep 200
  exit 95
fi

gda_gdasx_nsst=${DMPDIR}/gdasx.${PDY}/${cyc}/atmos/gdas.t${cyc}z.nsstbufr
gda_gfsx_nsst=${DMPDIR}/gfsx.${PDY}/${cyc}/atmos/gfs.t${cyc}z.nsstbufr
if [ -f $gda_gdasx_nsst ]; then
  echo "Found $gda_gdasx_nsst"
  #ecflow_client --event release_gdas_emc_prep
else
  sleep 200
  exit 93
fi
if [ -f $gda_gfsx_nsst ]; then
  echo "Found $gda_gfsx_nsst"
  #ecflow_client --event release_gfs_emc_prep
else
  sleep 200
  exit 93
fi

ic=1
release_gdas="NO"
ecflow_client --event release_gdas_emc_prep
release_gfs="NO"
ecflow_client --event release_gfs_emc_prep
release_enkfgdas="NO"
while [ $ic -le 20 ];
do
  if [ -s "$OBSPROC_GDAS_Trigger" -a -s "$IMSSNOW_GDAS_Trigger" -a -s "$COMIN_OBS_gdas" -a $release_gdas = "NO" ]; then
    release_gdas="YES"
    ecflow_client --event release_gdas
  fi
  if [ -s "$OBSPROC_GFS_Trigger" -a -s "$IMSSNOW_gfs_Trigger" -a -s "$COMIN_OBS_gfs" -a $release_gfs = "NO" ]; then
    release_gfs="YES"
    ecflow_client --event release_gfs
  fi
  if [ -s $COMIN_OBS_gdas ]; then
    release_enkfgdas="YES"
    ecflow_client --event release_enkfgdas
  fi
  if [ $release_gdas = "YES" -a $release_gfs = "YES" -a $release_enkfgdas = "YES" ]; then
    break
  fi
  ic=`expr $ic + 1`
  if [ $ic -gt 20 ]; then
    exit 99
  fi
  sleep 38
done

##############################################
# Ensure MetPlus input exist
##############################################
#release_fg_metpg2o1="NO"
#release_fg_metppcp1="NO"
#COMIN_vppg="/lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/global"
#COMIN_vppg_gdas=${COMIN_vppg}/archive/obs_data/prepbufr/gdas/prepbufr.gdas.${PDYm1}00
#COMIN_vppg_nam_PDY=${COMIN_vppg}/archive/obs_data/prepbufr/nam/nam.${PDY}        # /nam.t*z.prepbufr.tm*
#COMIN_vppg_nam_PDYm1=${COMIN_vppg}/archive/obs_data/prepbufr/nam/nam.${PDYm1}    # /nam.t*z.prepbufr.tm*
#COMIN_vppg_nam_PDYm2=${COMIN_vppg}/archive/obs_data/prepbufr/nam/nam.${PDYm2}    # /nam.t*z.prepbufr.tm*
#COMIN_vppg_ccpa=${COMIN_vppg}/archive/obs_data/ccpa_accum24hr/ccpa.${PDYm1}12.24h
#echo "Checking metpg2o1 input for prepbufr file on ${PDYm1}"
#ic=21
ecflow_client --event release_metplus
#while [ $ic -le 20 ];
#do
#  echo $COMIN_vppg_gdas
#  if [ -s $COMIN_vppg_gdas ]; then
#    cd $COMIN_vppg_nam_PDYm1
#    test_ct_1=`find . -name "nam.t*z.prepbufr.tm*"|wc -l`
#    cd $COMIN_vppg_nam_PDYm2
#    test_ct_2=`find . -name "nam.t*z.prepbufr.tm*"|wc -l`
#    if [ $test_ct_1 -eq 8 ]; then
#      if [ $test_ct_2 -eq 8 ]; then
#        release_fg_metpg2o1="YES"
#      fi
#    fi
#  fi
#  echo "Checking metppcp1 input for prepbufr file on ${PDYm1}"
#  if [ -s $COMIN_vppg_ccpa ]; then
#    release_fg_metppcp1="YES"
#  fi
#  if [ $release_fg_metpg2o1 = "YES" -a $release_fg_metppcp1 = "YES" ]; then
#    ecflow_client --event release_metplus
#    break
#  fi
#  ic=`expr $ic + 1`
#  if [ $ic -gt 20 ]; then
#    exit 99
#  fi
#  sleep 38
#done

echo "ENDED NORMALLY."

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0

